version: '3'
services:
  web:
    image: docker-node-express-mongoapp
    build: ./web-site
    command: nodemon --exec babel-node -- ./server.js
    ports:
      - "5000:5000"
    volumes:
      - ./web-site:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - "mongo"

  mongo:
    image: "mongo"
    ports:
      - "27017:27017"

  adminmongo:
    image: "mrvautin/adminmongo"
    ports:
      - "1234:1234"
